plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id 'jacoco'
}
group = 'ru.itone.illya4gurenko'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation("org.mockito:mockito-junit-jupiter:5.23.0")

    implementation("net.datafaker:datafaker:2.7.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.22.1")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.22.1")
    implementation 'org.slf4j:slf4j-api:2.0.18'
    implementation 'ch.qos.logback:logback-classic:1.6.0'

    implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'}

test {
    useJUnitPlatform()
}

sourceSets {
    test {
        java {
            srcDir 'src/test/java'
        }
        resources {
            srcDir 'src/test/resources'
        }
    }
    integrationTest {
        java {
            srcDir 'src/integrationTest/java'
            compileClasspath += sourceSets.main.output + configurations.testRuntimeClasspath
            runtimeClasspath += output + compileClasspath
        }

        resources {
            srcDir 'src/integrationTest/resources'
        }
    }
}

tasks.processTestResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}