version: '3.8'

services:
  generator-app:
    build: .
    container_name: file-generator-service
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - D:/gpb_tasks/shared_exchange:/app/generated
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - food_bridge

networks:
  food_bridge:
    external: true