
server.port=8080

file.out = ./generated

file.charset=UTF-8

faker.locale=ru

server.endpoint.post=/api/parametres

log.file-path=./logs/app.log

logback.config.path=./config/logback.xml

crypto.key.path=./config/secret.key

generator.file.percentage.invalid=50

file.send.chunked.enabled=true

receiver.url.chunked=https://webhook.site/38afd443-5edb-413b-89c9-8fa61d0a0b23
