
generator.files.server.port=8080

generator.files.file.out = ./generated

generator.files.file.charset=UTF-8

generator.files.faker.locale=ru

generator.files.server.endpoint.post=/api/parametres

generator.files.log.file-path=./logs/app.log

generator.files.logback.config.path=./config/file-logback.xml

generator.files.crypto.key.path=./config/secret.key

generator.files.percentage.invalid=40

generator.files.file.send.chunked.enabled=false

generator.files.file.send.multipart.enabled=false

generator.files.file.send.grpc.enabled=true

generator.files.grpc.receiver.url=localhost:9090

generator.files.receiver.url=http://localhost:8081/api/files/upload
